{"name": "Параметризированная проверка невозможности авторизации курьера, если неправильно указано одно из обязательных полей (login/password)", "status": "passed", "description": "Проверяем, что при попытке авторизации курьера с некорректно указанным одним из обязательных полей возвращается ошибка с кодом ответа 404, и текстом \"Учетная запись не найдена\"", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login_pass", "value": "['Maria98765', 'qwerty123']"}], "start": 1705859709396, "stop": 1705859709470}], "parameters": [{"name": "data", "value": "['Maria98765', 'qwerty123']"}], "start": 1705859709396, "stop": 1705859709471, "uuid": "27fbe6b1-5815-4291-9f0f-5ce0a5ec986b", "historyId": "732a3485648b7f737f2adb5a7ce4cdd7", "testCaseId": "378201d3eaaa7b564c47a8636770ad5e", "fullName": "tests.test_login_courier#test_negative_login_with_incorrect_required_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "36652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}